export const state = {
    zBuf: Array.from({ length: 240 }, () => Array(320).fill(null)),
    time: 0,
    sceneImageData: null,
    bgImageData: null,
    tint: {r: 0, g: 0, b: 0, a: 0},
    keys: new Set(),
    models: [
        {
            path: "models/forest.obj",
            materialPath: "models/forest.mtl",
            x: .4,
            y: .45,
            z: .3,
            yaw: 0,
            pitch: 0,
            roll: 0,
            scale: .5,
            points: [],
            uvs: [],
            meshes: [],
        },
    ],
    camera: { x: 0, y: 0, z: 0, yaw: 0, pitch: 0, roll: 0, forward: 0, right: 0, up: 0 },
};
