import getTextureImageData from "./canvas/load-texture.js";

export const state = {
    sceneImageData: null,
    models: [
        {
            path: "models/rat.obj",
            texture: "models/rat.png",
            x: -0.8,
            y: 0,
            z: 0.8,
            yaw: 0,
            pitch: 0,
            roll: 0,
            scale: 1,
            points: [],
            faces: [],
            uvs: [],
            textureImageData: await getTextureImageData("models/rat.png"),
        },
        {
            path: "models/rat.obj",
            texture: "models/rat.png",
            x: -0.5,
            y: 0,
            z: 0.8,
            yaw: 0,
            pitch: 0,
            roll: 0,
            scale: 1,
            points: [],
            faces: [],
            uvs: [],
            textureImageData: await getTextureImageData("models/rat.png"),
        },
        {
            path: "models/rat.obj",
            texture: "models/rat.png",
            x: -0.2,
            y: 0,
            z: 0.8,
            yaw: 0,
            pitch: 0,
            roll: 0,
            scale: 1,
            points: [],
            faces: [],
            uvs: [],
            textureImageData: await getTextureImageData("models/rat.png"),
        },

        {
            path: "models/rat.obj",
            texture: "models/rat.png",
            x: 0.0,
            y: 0,
            z: 0.8,
            yaw: 0,
            pitch: 0,
            roll: 0,
            scale: 1,
            points: [],
            faces: [],
            uvs: [],
            textureImageData: await getTextureImageData("models/rat.png"),
        },
        {
            path: "models/rat.obj",
            texture: "models/rat.png",
            x: 0.2,
            y: 0,
            z: 0.8,
            yaw: 0,
            pitch: 0,
            roll: 0,
            scale: 1,
            points: [],
            faces: [],
            uvs: [],
            textureImageData: await getTextureImageData("models/rat.png"),
        },
        {
            path: "models/rat.obj",
            texture: "models/rat.png",
            x: 0.5,
            y: 0,
            z: 0.8,
            yaw: 0,
            pitch: 0,
            roll: 0,
            scale: 2,
            points: [],
            faces: [],
            uvs: [],
            textureImageData: await getTextureImageData("models/rat.png"),
        },
        {
            path: "models/rat.obj",
            texture: "models/rat.png",
            x: 0.8,
            y: 0,
            z: 0.8,
            yaw: 0,
            pitch: 0,
            roll: 0,
            scale: 1,
            points: [],
            faces: [],
            uvs: [],
            textureImageData: await getTextureImageData("models/rat.png"),
        },
    ],
    camera: { x: 0, y: 0, z: -0.5, yaw: 0, pitch: 0, roll: 0 },
};
